name: gh-pages to master
on:
  push:	
    branches:	
      - Source

jobs:
  deploy:
    name: gh-pages to master
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@gh-pages

    - name: Deploy
      uses: s0/git-publish-subdir-action@master
      env:
        REPO: self
        BRANCH: master
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
